name = "afferent"
version = "0.1.0"
defaultTargets = ["afferent"]

[[require]]
name = "collimator"
git = "https://github.com/nathanial/collimator"
rev = "master"

[[lean_lib]]
name = "Afferent"
deps = ["collimator"]

[[lean_exe]]
name = "afferent"
root = "Main"
